# Generated by Django 2.2.4 on 2019-08-13 19:56

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import yandex_bs.imports.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('town', models.TextField(validators=[yandex_bs.imports.validators.ValidStringValidator()])),
                ('street', models.TextField(validators=[yandex_bs.imports.validators.ValidStringValidator()])),
                ('building', models.TextField(validators=[yandex_bs.imports.validators.ValidStringValidator()])),
                ('apartment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('relatives', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]), blank=True, size=None)),
                ('import_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='imports.ImportObject')),
            ],
        ),
    ]
